/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: n7aNyJLgg5UqcAEDnqHm8X
// Component: wHKtoZrzCYRH

import * as React from "react";
import { DefaultNewPageProps } from "./PlasmicNewPage"; // plasmic-import: wHKtoZrzCYRH/render

import { ClientNewPage } from "../../../app/new-page/page-client"; // plasmic-import: wHKtoZrzCYRH/rscClient

const $$ = {};

export type PageCtx = {
  pageRoute: string;
  pagePath: string;
  params: Record<string, string | string[] | undefined>;
  query: Record<string, string | string[] | undefined>;
};

export function generateDynamicMetadata($q: any, $ctx: PageCtx) {
  return {
    openGraph: {},
    twitter: {
      card: "summary" as const
    }
  };
}

function mkPathFromRouteAndParams(
  route: string,
  params: Record<string, string | string[] | undefined>
) {
  if (!params) {
    return route;
  }
  let path = route;
  for (const [key, value] of Object.entries(params)) {
    if (typeof value === "string") {
      path = path.replace(`[${key}]`, value);
    } else if (Array.isArray(value)) {
      if (path.includes(`[[...${key}]]`)) {
        path = path.replace(`[[...${key}]]`, value.join("/"));
      } else if (path.includes(`[...${key}]`)) {
        path = path.replace(`[...${key}]`, value.join("/"));
      }
    }
  }
  return path;
}

export interface NewPageServerSkeletonProps {
  params?: Promise<Record<string, string | string[] | undefined>>;
  searchParams?: Promise<Record<string, string | string[] | undefined>>;
}

export async function makeAppRouterPageCtx({
  params,
  searchParams
}: NewPageServerSkeletonProps) {
  const pageRoute = "/new-page";
  const pageParams = (await params) ?? {};
  const pagePath = mkPathFromRouteAndParams(pageRoute, pageParams);

  const ctx = {
    pageRoute,
    pagePath,
    params: pageParams,
    query: (await searchParams) ?? {}
  };
  return ctx;
}

export type PlasmicNewPageServerProps = DefaultNewPageProps &
  NewPageServerSkeletonProps;

export function PlasmicNewPageServer(props: PlasmicNewPageServerProps) {
  return <ClientNewPage {...props} />;
}
