/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: n7aNyJLgg5UqcAEDnqHm8X

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantsr1RO7PsPui } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: R1R_o7-PSPui/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantsr1RO7PsPui
});
