/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: n7aNyJLgg5UqcAEDnqHm8X
// Component: j-WUM6FzFAEB

import * as React from "react";
import { DefaultPruebaTableProps } from "./PlasmicPruebaTable"; // plasmic-import: j-WUM6FzFAEB/render

import { ClientPruebaTable } from "../../../app/prueba-table/page-client"; // plasmic-import: j-WUM6FzFAEB/rscClient

const $$ = {};

export type PageCtx = {
  pageRoute: string;
  pagePath: string;
  params: Record<string, string | string[] | undefined>;
  query: Record<string, string | string[] | undefined>;
};

export function generateDynamicMetadata($q: any, $ctx: PageCtx) {
  return {
    openGraph: {},
    twitter: {
      card: "summary" as const
    }
  };
}

function mkPathFromRouteAndParams(
  route: string,
  params: Record<string, string | string[] | undefined>
) {
  if (!params) {
    return route;
  }
  let path = route;
  for (const [key, value] of Object.entries(params)) {
    if (typeof value === "string") {
      path = path.replace(`[${key}]`, value);
    } else if (Array.isArray(value)) {
      if (path.includes(`[[...${key}]]`)) {
        path = path.replace(`[[...${key}]]`, value.join("/"));
      } else if (path.includes(`[...${key}]`)) {
        path = path.replace(`[...${key}]`, value.join("/"));
      }
    }
  }
  return path;
}

export interface PruebaTableServerSkeletonProps {
  params?: Promise<Record<string, string | string[] | undefined>>;
  searchParams?: Promise<Record<string, string | string[] | undefined>>;
}

export async function makeAppRouterPageCtx({
  params,
  searchParams
}: PruebaTableServerSkeletonProps) {
  const pageRoute = "/prueba-table";
  const pageParams = (await params) ?? {};
  const pagePath = mkPathFromRouteAndParams(pageRoute, pageParams);

  const ctx = {
    pageRoute,
    pagePath,
    params: pageParams,
    query: (await searchParams) ?? {}
  };
  return ctx;
}

export type PlasmicPruebaTableServerProps = DefaultPruebaTableProps &
  PruebaTableServerSkeletonProps;

export function PlasmicPruebaTableServer(props: PlasmicPruebaTableServerProps) {
  return <ClientPruebaTable {...props} />;
}
