/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: n7aNyJLgg5UqcAEDnqHm8X
// Component: sb55HXsakhYt

"use client";

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/navigation";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/host";
import * as plasmicAuth from "@plasmicapp/auth-react";

import { usePlasmicDataSourceContext } from "@plasmicapp/data-sources-context";

import { generateDynamicMetadata, PageCtx } from "./PlasmicLoginServer"; // plasmic-import: sb55HXsakhYt/rscServer

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: n7aNyJLgg5UqcAEDnqHm8X/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: n7aNyJLgg5UqcAEDnqHm8X/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: n7aNyJLgg5UqcAEDnqHm8X/projectcss
import sty from "./PlasmicLogin.module.css"; // plasmic-import: sb55HXsakhYt/css

import Icon3Icon from "./icons/PlasmicIcon__Icon3"; // plasmic-import: 5jMoYLQzB-BF/icon

const emptyProxy: any = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q: any): any {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

createPlasmicElementProxy;

export type PlasmicLogin__VariantMembers = {};
export type PlasmicLogin__VariantsArgs = {};
type VariantPropType = keyof PlasmicLogin__VariantsArgs;
export const PlasmicLogin__VariantProps = new Array<VariantPropType>();

export type PlasmicLogin__ArgsType = {};
type ArgPropType = keyof PlasmicLogin__ArgsType;
export const PlasmicLogin__ArgProps = new Array<ArgPropType>();

export type PlasmicLogin__OverridesType = {
  root?: Flex__<"div">;
  svg?: Flex__<"svg">;
  h1?: Flex__<"h1">;
  p?: Flex__<"p">;
  form?: Flex__<"form">;
  textbox?: Flex__<"input">;
  textbox2?: Flex__<"input">;
  link?: Flex__<"a"> & Partial<LinkProps>;
  button?: Flex__<"button">;
};

export interface DefaultLoginProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicLogin__RenderFunc(props: {
  variants: PlasmicLogin__VariantsArgs;
  args: PlasmicLogin__ArgsType;
  overrides: PlasmicLogin__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "textbox.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "textbox2.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });

  const pageMetadata = generateDynamicMetadata(
    wrapQueriesWithLoadingProxy({}),
    $ctx as PageCtx
  );

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <div className={classNames(projectcss.all, sty.freeBox__e5MhZ)}>
            <div className={classNames(projectcss.all, sty.freeBox__adTqf)}>
              <div className={classNames(projectcss.all, sty.freeBox__n98Fv)}>
                <Icon3Icon
                  data-plasmic-name={"svg"}
                  data-plasmic-override={overrides.svg}
                  className={classNames(projectcss.all, sty.svg)}
                  role={"img"}
                  style={{ fill: "var(--token-yC7LiU6hC0Ek)" }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__uUruf)}>
                <h1
                  data-plasmic-name={"h1"}
                  data-plasmic-override={overrides.h1}
                  className={classNames(
                    projectcss.all,
                    projectcss.h1,
                    projectcss.h1__n7aNy,
                    projectcss.__wab_text,
                    sty.h1
                  )}
                >
                  {"Bienvenido"}
                </h1>
                <p
                  data-plasmic-name={"p"}
                  data-plasmic-override={overrides.p}
                  className={classNames(
                    projectcss.all,
                    projectcss.p,
                    projectcss.p__n7aNy,
                    projectcss.__wab_text,
                    sty.p
                  )}
                >
                  {"Ingresa tu usuario y contrase\u00f1a"}
                </p>
              </div>
              <form
                data-plasmic-name={"form"}
                data-plasmic-override={overrides.form}
                className={classNames(projectcss.all, sty.form)}
              >
                <div
                  className={classNames(projectcss.all, sty.freeBox___7Gf5W)}
                >
                  <label
                    className={classNames(projectcss.all, sty.label__fmJXy)}
                  >
                    <span
                      className={classNames(
                        projectcss.all,
                        projectcss.span,
                        projectcss.span__n7aNy,
                        projectcss.__wab_text,
                        sty.span__gBoIv
                      )}
                    >
                      {"Correo"}
                    </span>
                  </label>
                  <input
                    data-plasmic-name={"textbox"}
                    data-plasmic-override={overrides.textbox}
                    className={classNames(
                      projectcss.all,
                      projectcss.input,
                      projectcss.input__n7aNy,
                      sty.textbox
                    )}
                    onChange={async (...eventArgs: any) => {
                      (e => {
                        generateStateOnChangeProp($state, ["textbox", "value"])(
                          e.target.value
                        );
                      }).apply(null, eventArgs);
                    }}
                    ref={ref => {
                      $refs["textbox"] = ref;
                    }}
                    value={
                      generateStateValueProp($state, ["textbox", "value"]) ?? ""
                    }
                  />
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__eXmg0)}>
                  <label
                    className={classNames(projectcss.all, sty.label___5JkaX)}
                  >
                    <span
                      className={classNames(
                        projectcss.all,
                        projectcss.span,
                        projectcss.span__n7aNy,
                        projectcss.__wab_text,
                        sty.span__yIjbU
                      )}
                    >
                      {"Contrase\u00f1a"}
                    </span>
                  </label>
                  <input
                    data-plasmic-name={"textbox2"}
                    data-plasmic-override={overrides.textbox2}
                    className={classNames(
                      projectcss.all,
                      projectcss.input,
                      projectcss.input__n7aNy,
                      sty.textbox2
                    )}
                    onChange={async (...eventArgs: any) => {
                      (e => {
                        generateStateOnChangeProp($state, [
                          "textbox2",
                          "value"
                        ])(e.target.value);
                      }).apply(null, eventArgs);
                    }}
                    ref={ref => {
                      $refs["textbox2"] = ref;
                    }}
                    value={
                      generateStateValueProp($state, ["textbox2", "value"]) ??
                      ""
                    }
                  />
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__klqix)}>
                  <PlasmicLink__
                    data-plasmic-name={"link"}
                    data-plasmic-override={overrides.link}
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.a__n7aNy,
                      sty.link
                    )}
                    component={Link}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    <span
                      className={classNames(
                        projectcss.all,
                        projectcss.span,
                        projectcss.span__n7aNy,
                        projectcss.__wab_text,
                        sty.span__qsJqw
                      )}
                    >
                      {"Olvid\u00e9 mi contrase\u00f1a"}
                    </span>
                  </PlasmicLink__>
                </div>
                <button
                  data-plasmic-name={"button"}
                  data-plasmic-override={overrides.button}
                  className={classNames(
                    projectcss.all,
                    projectcss.button,
                    projectcss.button__n7aNy,
                    sty.button
                  )}
                >
                  <span
                    className={classNames(
                      projectcss.all,
                      projectcss.span,
                      projectcss.span__n7aNy,
                      projectcss.__wab_text,
                      sty.span___5Sq8J
                    )}
                  >
                    {"Iniciar sesi\u00f3n"}
                  </span>
                </button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "svg",
    "h1",
    "p",
    "form",
    "textbox",
    "textbox2",
    "link",
    "button"
  ],
  svg: ["svg"],
  h1: ["h1"],
  p: ["p"],
  form: ["form", "textbox", "textbox2", "link", "button"],
  textbox: ["textbox"],
  textbox2: ["textbox2"],
  link: ["link"],
  button: ["button"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  svg: "svg";
  h1: "h1";
  p: "p";
  form: "form";
  textbox: "input";
  textbox2: "input";
  link: "a";
  button: "button";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicLogin__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicLogin__VariantsArgs;
    args?: PlasmicLogin__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicLogin__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicLogin__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicLogin__ArgProps,
          internalVariantPropNames: PlasmicLogin__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicLogin__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicLogin";
  } else {
    func.displayName = `PlasmicLogin.${nodeName}`;
  }
  return func;
}

function withUsePlasmicAuth<P extends object>(
  WrappedComponent: React.ComponentType<P>
) {
  const WithUsePlasmicAuthComponent: React.FC<P> = props => {
    const dataSourceCtx = usePlasmicDataSourceContext() ?? {};
    const { isUserLoading, user, token } = plasmicAuth.usePlasmicAuth({
      appId: "n7aNyJLgg5UqcAEDnqHm8X"
    });

    return (
      <PlasmicDataSourceContextProvider__
        value={{
          ...dataSourceCtx,
          isUserLoading,
          userAuthToken: token,
          user
        }}
      >
        <WrappedComponent {...props} />
      </PlasmicDataSourceContextProvider__>
    );
  };
  return WithUsePlasmicAuthComponent;
}

export const PlasmicLogin = Object.assign(
  // Top-level PlasmicLogin renders the root element
  withUsePlasmicAuth(makeNodeComponent("root")),
  {
    // Helper components rendering sub-elements
    svg: makeNodeComponent("svg"),
    h1: makeNodeComponent("h1"),
    p: makeNodeComponent("p"),
    form: makeNodeComponent("form"),
    textbox: makeNodeComponent("textbox"),
    textbox2: makeNodeComponent("textbox2"),
    link: makeNodeComponent("link"),
    button: makeNodeComponent("button"),

    // Metadata about props expected for PlasmicLogin
    internalVariantProps: PlasmicLogin__VariantProps,
    internalArgProps: PlasmicLogin__ArgProps,

    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pageRoute: "/login",
      pagePath: "/login",
      params: {},
      query: {}
    })
  }
);

export default PlasmicLogin;
/* prettier-ignore-end */
