// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.

import * as React from "react";
import { PageParamsProvider as PageParamsProvider__ } from "@plasmicapp/host";

import GlobalContextsProvider from "../components/plasmic/camas_sinai_control/PlasmicGlobalContextsProvider";

import AppLayout from "@/components/AppLayout";

import {
  PlasmicHomepageServer,
  makeAppRouterPageCtx,
  generateDynamicMetadata,
  HomepageServerSkeletonProps
} from "../components/plasmic/camas_sinai_control/PlasmicHomepageServer";

import type { Metadata, ResolvingMetadata } from "next";


export async function generateMetadata(
  { params, searchParams }: HomepageServerSkeletonProps,
  parent: ResolvingMetadata
): Promise<Metadata> {

  const ctx = await makeAppRouterPageCtx({
    params,
    searchParams
  });

  const metadata = generateDynamicMetadata({}, ctx);

  return {
    ...(await parent),
    ...metadata
  } as unknown as Metadata;
}


async function Homepage({ params, searchParams }: HomepageServerSkeletonProps) {

  const resolvedParams = await params;
  const resolvedSearchParams = await searchParams;

  return (

    <GlobalContextsProvider>

      <AppLayout>

        <PageParamsProvider__
          route="/"
          params={resolvedParams}
          query={resolvedSearchParams}
        >

          <PlasmicHomepageServer />

        </PageParamsProvider__>

      </AppLayout>

    </GlobalContextsProvider>

  );
}

export default Homepage;